# Generated by Django 4.1.7 on 2023-02-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='image',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='booking',
            name='traveler',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='travel.traveler'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='traveler/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(default=1, max_length=255),
        ),
    ]
