# Generated by Django 4.1.7 on 2023-02-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_rename_image_company_logo_booking_traveler_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Agency',
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
    ]
