# Generated by Django 4.1.7 on 2023-02-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_rename_company_agency_alter_agency_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='agency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='travel.agency'),
        ),
    ]
