# Generated by Django 4.1.7 on 2023-02-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_agency_uid_booking_uid_city_uid_country_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='city',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='country',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='uid',
        ),
    ]
