# Generated by Django 4.1.7 on 2023-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_remove_agency_uid_remove_booking_uid_remove_city_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='something',
            field=models.CharField(default='2', max_length=200),
        ),
    ]
