# Generated by Django 4.1.7 on 2023-02-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_agency_something'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='something',
        ),
    ]
