# Generated by Django 4.1.7 on 2023-02-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_remove_country_city_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='agency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='travel.agency'),
        ),
    ]
