# Generated by Django 4.1.7 on 2023-02-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_trip_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.traveler'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.trip'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='traveler/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='travel.agency'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
