# Generated by Django 4.1.7 on 2023-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_agency_logo_alter_booking_traveler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trip/', verbose_name='image'),
        ),
    ]
